name: Build

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - uses: android-actions/setup-android@v3
    - if: contains(matrix.os, 'ubuntu')
      name: Install Linux build dependencies
      run: |
        sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils
    - name: Install npm dependencies
      run: npm i --legacy-peer-deps
    - name: Download adb
      run: npm run adb
    - name: Build server
      run: npm run server
    - name: Download scrcpy
      run: npm run scrcpy
    - name: Build app
      run: npm run build
    - name: Package
      run: npm run pack
      env:
        CSC_LINK: ${{ secrets.CSC_LINK }}
        CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ matrix.os }}
        path: |
          release/**/*.exe
          release/**/*.deb
          release/**/*.AppImage
          release/**/*-lates*.yml
          !release/**/win-unpacked/
